FROM selenium/standalone-edge:120.0

USER root

RUN apt-get update && apt-get install -y python3-pip

WORKDIR /app

COPY requirements.txt .
RUN /usr/bin/python3 -m pip install --no-cache-dir -r requirements.txt

COPY main.py my_selenium.py ./
CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0"]